name: motionpath_core
description: Pure Dart MotionPath v4 animation engine.
version: 0.1.0
repository: https://github.com/chahyasantoso/motionpath-flutter
issue_tracker: https://github.com/chahyasantoso/motionpath-flutter/issues
documentation: https://github.com/chahyasantoso/motionpath-flutter/tree/main/docs
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  meta: ^1.12.0
dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
