import 'package:flutter/material.dart';
import 'package:motionpath_core/motionpath_core.dart';
import 'tower_defense_scene.dart';

class TowerDefenseDemoPage extends StatefulWidget { const TowerDefenseDemoPage({super.key}); @override State<TowerDefenseDemoPage> createState()=>_TowerDefenseDemoPageState(); }
class _TowerDefenseDemoPageState extends State<TowerDefenseDemoPage> with SingleTickerProviderStateMixin {
  late final MotionPathTrackRuntime _lane1,_lane2,_pulse; late final AnimationController _clock; bool _playing=false; int _wave=0; int _score=0; int _lives=20;
  @override void initState(){super.initState();final tracks=towerDefenseSceneTracks();_lane1=tracks[0];_lane2=tracks[1];_pulse=tracks[2];_clock=AnimationController(vsync:this,duration:const Duration(seconds:2))..addListener((){if(_playing){_lane1.seek(_clock.value);_lane2.seek((_clock.value+0.18).clamp(0.0,1.0));_pulse.seek((_clock.value*1.25)%1);setState((){});}});}
  void _start(){setState((){_playing=true;_wave++;});_clock.repeat();}
  void _reset(){_clock.stop();setState((){_playing=false;_wave=0;_score=0;_lives=20;});}
  @override void dispose(){_clock.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF070A12),appBar:AppBar(title:const Text('MotionPath Tower Defense')),body:Center(child:SizedBox(width:900,height:560,child:Stack(children:[CustomPaint(size:const Size(900,500),painter:_Lanes()),Positioned(left:200,top:210,child:_Tower('ARC CANNON',const Color(0xFF00F2FE))),Positioned(left:430,top:180,child:_Tower('PLASMA SPIRE',const Color(0xFFFF6BCB))),Positioned(left:660,top:230,child:_Tower('QUANTUM RAY',const Color(0xFFF5A623))),if(_playing)Positioned(left:(_lane1.compose()['x'] as num?)?.toDouble()??0,top:(_lane1.compose()['y'] as num?)?.toDouble()??150,child:const Text('👾',style:TextStyle(fontSize:30))),if(!_playing)Center(child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Wave ${_wave+1} Ready'),const SizedBox(height:8),const Text('Pre-placed energy towers are online.'),const SizedBox(height:16),ElevatedButton(onPressed:_start,child:const Text('Start Wave'))])))),if(_playing)Positioned(right:24,top:24,child:ElevatedButton(onPressed:_reset,child:const Text('Reset'))),Positioned(left:24,top:24,child:Text('Score $_score   Wave $_wave / 5   Lives $_lives',style:const TextStyle(fontSize:18))),]))));
}
class _Tower extends StatelessWidget{const _Tower(this.name,this.color);final String name;final Color color;@override Widget build(BuildContext context)=>Column(children:[Container(width:64,height:64,decoration:BoxDecoration(shape:BoxShape.circle,color:color.withValues(alpha:.2),border:Border.all(color:color,width:2),boxShadow:[BoxShadow(color:color.withValues(alpha:.5),blurRadius:18)]),child:const Center(child:Text('🗼',style:TextStyle(fontSize:28)))),Text(name,style:TextStyle(color:color,fontSize:10))]);}
class _Lanes extends CustomPainter{const _Lanes();@override void paint(Canvas c,Size s){final p=Paint()..color=const Color(0x447C5CFF)..style=PaintingStyle.stroke..strokeWidth=2; c.drawLine(const Offset(0,150),const Offset(900,200),p);c.drawLine(const Offset(0,350),const Offset(900,300),p);}@override bool shouldRepaint(covariant _Lanes old)=>false;}
